# Compute performance metrics for the given Y and Y_score without sklearn


# A.

import data using pandas

In [56]:
import numpy as np
import pandas as pd
data=pd.read_csv("a.csv")
data.tail(10)


y     proba
10090  1.0  0.811290
10091  1.0  0.675153
10092  1.0  0.618778
10093  1.0  0.767706
10094  1.0  0.508784
10095  1.0  0.665371
10096  1.0  0.607961
10097  1.0  0.777724
10098  1.0  0.846036
10099  1.0  0.679507

sorted data by increasing order of probabilities

In [58]:
data = data.sort_values(by='proba' ,kind='mergesort')


reset index to data from zero

In [59]:
data.reset_index(inplace=True)


data contains 10100 rows and 3 columns

In [60]:
data.shape

(10100, 3)

for predicted probabilities in data put zero if proba <0.5 else put one

In [61]:
f = lambda x: 0 if x<0.5 else 1
data['proba'] = data['proba'].map(f)

data is imbalance type data<br>
where no of 'ones'>>>>>>>> no of 'zeros'

In [62]:
data.proba.value_counts()

1    10100
Name: proba, dtype: int64

In [63]:
data.y.value_counts()

1.0    10000
0.0      100
Name: y, dtype: int64

In [64]:
data.head()

index    y  proba
0   5012  1.0      1
1    805  1.0      1
2   7421  1.0      1
3   1630  1.0      1
4   8294  1.0      1

In [66]:
actual=data.y
predicted=data.proba

# 1.Confusion Matrix 

Custom implementation of confusion matrix<br>
confusion matrix consists of matrix of elements namely True Positive,False Positive,False Negative,True Negative<br>
which shows how many points correctly classified and vice versa

In [68]:
from tqdm import tqdm
TP=0
FP=0
FN=0
TN=0


for i in tqdm(range(len(data))):
    if (actual[i]==1 and predicted[i]==1):
        TP +=1
    elif (actual[i]==0 and predicted[i]==1):
        FP +=1
    elif (actual[i]==1 and predicted[i]==0):
        FN +=1
    elif (actual[i]==0 and predicted[i]==0):
        TN +=1
        

A=np.array([[TP,FP],[FN,TN]])
print(A)




100%|██████████████████████████████████| 10100/10100 [00:01<00:00, 9265.71it/s]


[[10000   100]
 [    0     0]]


sklearn implementation of confusion matrix<br>
cross check and thus we get same result irrespective of positions of points

In [69]:
from sklearn.metrics import confusion_matrix
confusion_matrix(actual, predicted)


array([[    0,   100],
       [    0, 10000]], dtype=int64)

# 2. F1 Score 


F1-score means a statistical measure of the accuracy of a test or an individual. 
It is composed of two primary attributes, viz. precision and recall, both calculated as percentages and combined as 
harmonic mean to assign a single number, easy for comprehension.<br>
Recall=True positive/(True positive+False Negative)<br>
Precision=True positive/(True positive+False positive)<br>
F1 is usually more useful than accuracy, especially if you have an uneven class distribution.

In [70]:
TPFN=0
TP=0
TPFP=0
for i in range(len(data)):
    if actual[i]==1 and predicted[i]==1:
        TP+=1

for i in range(len(data)):
    if actual[i]==1 :
        TPFN+=1
for i in range(len(data)):
    if predicted[i]==1 :
        TPFP+=1

        
        
        
        
#print(TPFN)
#print(TP)
        
Recall=TP/TPFN  
print(Recall)


precision=TP/TPFP
print(precision)

1.0
0.9900990099009901


High precision relates to the low false positive rate. We have got 0.99 precision which is pretty good.

We have got recall of 1.0 which is good for  model as it’s above 0.5.

In [71]:
F1_Score=(2*(Recall*precision))/(Recall+precision)
print(F1_Score)

0.9950248756218906


Cross check using sklearn implementation and got correct results

In [72]:
sklearn.metrics.recall_score(actual, predicted)

1.0

In [73]:
sklearn.metrics.precision_score(actual, predicted)


0.9900990099009901

In [74]:
sklearn.metrics.f1_score(actual, predicted)

0.9950248756218906

# 3. AUC Score

Test with perfect accuracy has an AUC of 1<br>
The area under the ROC curve, or AUC, is used as a measure of classifier performance<br>
AUC=0.5  is the accuracy of making classification decisions

In [10]:
data.head()

index    y     proba
0   5012  1.0  0.500019
1    805  1.0  0.500047
2   7421  1.0  0.500058
3   1630  1.0  0.500058
4   8294  1.0  0.500081

In [11]:
data.shape

(10100, 3)

In [12]:
import numpy as np
proba=data.proba
from  tqdm import tqdm
act=data.y
V=[]
D=[]
len(proba)
for i in tqdm(range (len(proba))):
    A=[]
    for j in proba:
        if proba[i]<= j: 
            A.append(1)
        else:
            A.append(0)
    TP=0
    FN=0
    FP=0
    TN=0
    for i in range(len(act)):
        if (act[i]==1 and A[i]==1):
            TP +=1
        elif (act[i]==0 and A[i]==1):
            FP +=1
        elif (act[i]==1 and A[i]==0):
            FN +=1
        elif (act[i]==0 and A[i]==0):
            TN +=1

    TPR=TP/(TP+FN)
    V.append(TPR)
    FPR=FP/(FP+TN)
    D.append(FPR)
tpr_arr=np.array(V)
fpr_arr=np.array(D)
print(type(tpr_arr))#print(TPR)
    
    #print(FPR)
    #print("****************")
print(np.trapz(tpr_arr, fpr_arr))
print(tpr_arr)
print(fpr_arr)
pass

100%|██████████████████████████████████| 10100/10100 [1:52:56<00:00,  1.49it/s]


<class 'numpy.ndarray'>
-0.48829900000000004
[1.000e+00 9.999e-01 9.998e-01 ... 3.000e-04 2.000e-04 1.000e-04]
[1. 1. 1. ... 0. 0. 0.]


We ,got AUC =0.48 near to 0.5.

Sklearn implementation of AUC to cross check<br>
Thus we get exact results

In [13]:
import numpy as np
from sklearn.metrics import roc_auc_score
roc_auc_score(data.y, data.proba)

0.48829900000000004

# 4.Accuracy Score


Accuracy score basically means ratio of number of points correctly classified to Total number of Points.<br>
which means, Accuracy Score=(TP+TN)/(TP+TN+FP+FN)

In [75]:
Accuracy_score=(TP+TN)/(TP+TN+FP+FN)
print(Accuracy_score)

0.9900990099009901


Sklearn implementation of Accuracy Score<br>
cross check and thus we get exact results

In [76]:
import sklearn
sklearn.metrics.accuracy_score(actual, predicted, normalize=True, sample_weight=None)

0.9900990099009901

In [126]:
import pandas as pd
import numpy as np
data=pd.read_csv("d.csv")
data.head(20)

y   pred
0   101.0  100.0
1   120.0  100.0
2   131.0  113.0
3   164.0  125.0
4   154.0  152.0
5   133.0  153.0
6   148.0  139.0
7   172.0  145.0
8   153.0  162.0
9   162.0  154.0
10  200.0  160.0
11  169.0  186.0
12  149.0  173.0
13  168.0  157.0
14  174.0  163.0
15  130.0  168.0
16  130.0  141.0
17  131.0  133.0
18  114.0  130.0
19  119.0  117.0

In [127]:
n=len(data)
print(n)

157200


Data contains 157200 rows and 2 columns

In [128]:
data.shape

(157200, 2)

In [129]:
A=data.y
B=data.pred

# 1.Mean Square Error

The mean squared error tells you how close a regression line is to a set of points. It does this by taking the distances from the points to the regression line (these distances are the “errors”) and squaring them. The squaring is necessary to remove any negative signs.

In [130]:
sum_errr=0
for i in range(len(data)):
    err=(A[i]-B[i])*(A[i]-B[i])
    sum_errr+=err
    
mean_sq_er=(1/n)*sum_errr
print(mean_sq_er)

177.16569974554707


Sklearn implementation which shows we got exact result

In [131]:
from sklearn.metrics import mean_squared_error
mean_squared_error(A, B)


177.16569974554707

# 2. MAPE

The mean absolute percentage error (MAPE) is the mean or average of the absolute percentage errors of forecasts.

The formulae for MAPE is =Summation(((Actual_val-Predicted_val)/Actual_val)*100)/Total no of points in data<br>
But,What if Actual_val==0,than summation will gets false ,To avoid this problem we took average of all actual points and replace
Actual_val in denometer of MAPE formulae by this average

In [132]:
a=0

for i in tqdm(range(len(data))):
    a+=A[i]
#print(a)
a_dash=a/n
#print(a_dash)

abs_err_sum=0
for i in range(len(data)):
    abs_val=abs(A[i]-B[i])
    abs_err_sum+=abs_val
    
MAPE=(abs_err_sum * 100)/(a_dash *n )
print(MAPE)


100%|███████████████████████████████| 157200/157200 [00:07<00:00, 21865.71it/s]


12.91202994009687


# 3. R^2 error

R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination, or the coefficient of multiple determination for multiple regression.<br>

The definition of R-squared is fairly straight-forward; it is the percentage of the response variable variation that is explained by a linear model. Or:<br>

R-squared = Explained variation / Total variation

In [133]:
from tqdm import tqdm
a=0


for i in tqdm(range(len(data))):
    a+=A[i]
A_dash=a/n
    
#print(A_dash)
SS_tot=0
for i in tqdm(range(len(data))):
    s=(A[i]-A_dash)*(A[i]-A_dash)
    SS_tot+=s

#print(SS_tot)

SS_res=0
for i in tqdm(range(len(data))):
    s=(A[i]-B[i])*(A[i]-B[i])
    SS_res+=s
#print(SS_res)

A=SS_res/SS_tot
R_sqr_err=1-A
print(R_sqr_err)
    

100%|███████████████████████████████| 157200/157200 [00:15<00:00, 10134.07it/s]


0.9563582786990964
